name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - feature-inicial
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"  # Mantido consistente com main.yml

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run tests
        run: |
          pip install pytest
          # Incluindo a raiz do projeto no PYTHONPATH
          if [ -d tests ]; then PYTHONPATH=. pytest --maxfail=1 --disable-warnings -q; else echo "Nenhum teste encontrado"; fi

  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          if [ -f Dockerfile ]; then docker build -t my-app:test .; else echo "Dockerfile não encontrado"; fi
